apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pingpong-hpa
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: pingpong-rollout
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50